DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (
   ID INT AUTO_INCREMENT PRIMARY KEY;
   MATRICULA VARCHAR(100) UNIQUE NOT NULL,
   NOMBRE VARCHAR(100) NOT NULL,
   APELLIDO VARCHAR(100) NOT NULL
);
